name:                gemssearch002
version:             0.1.0.0
github:              "githubuser/gemssearch002"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gemssearch002#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- array
- hashable
- psqueues
- containers
- transformers
- unordered-containers
- exceptions

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -ddump-to-file
- -ddump-simpl

language: GHC2024
default-extensions:
- Strict

library:
  source-dirs: src

executables:
  gemssearch002-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gemssearch002
    - unliftio

tests:
  gemssearch002-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gemssearch002
    - hspec
